-- ============================================================================
-- Migration: Create ENUM Types
-- Description: Creates custom ENUM types for flashcard source and status
-- Tables affected: flashcards (will use these enums)
-- Dependencies: None
-- ============================================================================

-- enum for tracking the origin of flashcard creation
-- 'manual' - flashcard created directly by user through UI
-- 'ai_generated' - flashcard generated by AI from source text
create type flashcard_source_enum as enum ('manual', 'ai_generated');

-- enum for tracking flashcard lifecycle status
-- 'active' - flashcard is ready for learning and included in study sessions
-- 'pending_review' - flashcard generated by AI, awaiting user acceptance/rejection
-- 'rejected' - flashcard rejected by user (kept for analytics purposes)
create type flashcard_status_enum as enum ('active', 'pending_review', 'rejected');

